'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var k=a.length,d=0;d<k;d++){var e=a[d];if(c.call(b,e,d,a))return{i:d,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};
$jscomp.polyfill=function(a,c,b,k){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,k):$jscomp.polyfillUnisolated(a,c,b,k))};$jscomp.polyfillUnisolated=function(a,c,b,k){b=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var d=a[k];if(!(d in b))return;b=b[d]}a=a[a.length-1];k=b[a];c=c(k);c!=k&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,k){var d=a.split(".");a=1===d.length;k=d[0];k=!a&&k in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var e=0;e<d.length-1;e++){var g=d[e];if(!(g in k))return;k=k[g]}d=d[d.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?k[d]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:c}):c!==b&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(k,d,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var c=function(d,e){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};c.prototype.toString=function(){return this.$jscomp$symbol$id_};var b=0,k=function(d){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(d||"")+"_"+b++,d)};return k},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),b=0;b<c.length;b++){var k=$jscomp.global[c[b]];"function"===typeof k&&"function"!=typeof k.prototype[a]&&$jscomp.defineProperty(k.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){a instanceof String&&(a+="");var b=0,k={next:function(){if(b<a.length){var d=b++;return{value:c(d,a[d]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");var SVG_ARROW_POLYGON="0,3 12,3 12,0 18,5 12,10 12,7 0,7",SVG_ARROW_HEIGHT=10,curVisualizerID=1;
function ExecutionVisualizer(a,c,b){this.curInputCode=c.code.rtrim();this.curTrace=c.trace;this.DEFAULT_EMBEDDED_CODE_DIV_WIDTH=350;this.DEFAULT_EMBEDDED_CODE_DIV_HEIGHT=400;0<this.curTrace.length&&(c=this.curTrace[this.curTrace.length-1],"raw_input"==c.event?(this.promptForUserInput=!0,this.userInputPromptStr=htmlspecialchars(c.prompt),this.curTrace.pop()):"mouse_input"==c.event&&(this.promptForMouseInput=!0,this.userInputPromptStr=htmlspecialchars(c.prompt),this.curTrace.pop()));this.curInstr=0;
this.params=b;this.params||(this.params={});b=void 0!==this.params.arrowLines;c=void 0!==this.params.highlightLines;b||c?b&&c||(b?this.params.highlightLines=!this.params.arrowLines:this.params.arrowLines=!this.params.highlightLines):(this.params.highlightLines=!1,this.params.arrowLines=!0);this.compactFuncLabels=this.params.compactFuncLabels;this.params.pyCrazyMode&&(this.params.arrowLines=this.params.highlightLines=!1);this.params.visualizerIdOverride?this.visualizerID=this.params.visualizerIdOverride:
(this.visualizerID=curVisualizerID,curVisualizerID++);this.leftGutterSvgInitialized=!1;this.codeRowHeight=this.arrowOffsetY=void 0;this.disableHeapNesting=1==this.params.disableHeapNesting;this.drawParentPointers=1==this.params.drawParentPointers;this.textualMemoryLabels=1==this.params.textualMemoryLabels;this.showOnlyOutputs=1==this.params.showOnlyOutputs;this.tabularView=1==this.params.tabularView;this.showAllFrameLabels=1==this.params.showAllFrameLabels;this.executeCodeWithRawInputFunc=this.params.executeCodeWithRawInputFunc;
this.jsPlumbInstance=jsPlumb.getInstance({Endpoint:["Dot",{radius:3}],EndpointStyles:[{fillStyle:connectorBaseColor},{fillstyle:null}],Anchors:["RightMiddle","LeftMiddle"],PaintStyle:{lineWidth:1,strokeStyle:connectorBaseColor},Connector:["StateMachine"],Overlays:[["Arrow",{length:10,width:7,foldback:.55,location:1}]],EndpointHoverStyles:[{fillStyle:connectorHighlightColor},{fillstyle:null}],HoverPaintStyle:{lineWidth:1,strokeStyle:connectorHighlightColor}});this.domRoot=$("#"+a);this.domRoot.data("vis",
this);this.domRootD3=d3.select("#"+a);this.domRoot.html('<div class="ExecutionVisualizer"></div>');this.domRoot=this.domRoot.find("div.ExecutionVisualizer");this.domRootD3=this.domRootD3.select("div.ExecutionVisualizer");this.breakpoints=this.codeOutputLines=null;this.sortedBreakpointsList=[];this.classAttrsHidden={};this.pytutor_hooks={};"java"===this.params.lang&&this.activateJavaFrontend();this.numStdoutLines=0;var k;for(a=this.curTrace.length-1;0<=a&&!(k=this.curTrace[a].stdout);a--);k&&(this.numStdoutLines=
k.rtrim().split("\n").length);this.try_hook("end_constructor",{myViz:this});this.hasRendered=!1;this.render()}ExecutionVisualizer.prototype.add_pytutor_hook=function(a,c){this.pytutor_hooks[a]?this.pytutor_hooks[a].push(c):this.pytutor_hooks[a]=[c]};ExecutionVisualizer.prototype.try_hook=function(a,c){if(this.pytutor_hooks[a])for(var b=0;b<this.pytutor_hooks[a].length;b++){var k=this.pytutor_hooks[a][b].apply(null,[c]);if(k&&k[0])return k}return[!1]};
ExecutionVisualizer.prototype.resetJsPlumbManager=function(){this.jsPlumbManager={heap_pointer_src_id:1,connectionEndpointIDs:d3.map(),heapConnectionEndpointIDs:d3.map(),parentPointerConnectionEndpointIDs:d3.map(),renderedHeapObjectIDs:d3.map()}};ExecutionVisualizer.prototype.generateID=function(a){return"v"+this.visualizerID+"__"+a};ExecutionVisualizer.prototype.generateHeapObjID=function(a,c){return this.generateID("heap_object_"+a+"_s"+c)};
ExecutionVisualizer.prototype.render=function(){if(this.hasRendered)alert("ERROR: You should only call render() ONCE on an ExecutionVisualizer object.");else{var a=this,c='<div id="dataViz">       <table id="stackHeapTable">         <tr>           <td id="stack_td">             <div id="globals_area">               <div id="stackHeader">Frames</div>             </div>             <div id="stack"></div>           </td>           <td id="heap_td">             <div id="heap">               <div id="heapHeader">Objects</div>             </div>           </td>         </tr>       </table>     </div>';
a.tabularView&&(c='<div id="optTabularView"></div>');this.params.verticalStack?this.domRoot.html('<div id="vizHeader">       <textarea class="vizTitleText" id="vizTitleEditor" cols="60" rows="1"></textarea>       <div class="vizTitleText" id="vizTitleViewer"></div>       <textarea class="vizDescriptionText" id="vizDescriptionEditor" cols="75" rows="2"></textarea>       <div class="vizDescriptionText" id="vizDescriptionViewer"></div>    </div><table border="0" class="visualizer"><tr><td class="vizLayoutTd" id="vizLayoutTdFirst""><div id="codeDisplayDiv">       <div id="langDisplayDiv"></div>       <div id="pyCodeOutputDiv"/>       <div id="editCodeLinkDiv"><a id="editBtn">Edit code</a>       <span id="liveModeSpan" style="display: none;">| <a id="editLiveModeBtn" href="#">Live programming</a></a>       </div>       <div id="legendDiv"/>       <div id="rawUserInputDiv">       <span id="userInputPromptStr"/>       <input type="text" id="raw_input_textbox" size="30"/>       <button id="raw_input_submit_btn">Submit</button>     </div>       <div id="executionSliderDocs"><font color="#e93f34">NEW!</font> Click on a line of code to set a breakpoint. Then use the Forward and Back buttons to jump there.</div>     </div>     <div id="executionSlider"/>     <div id="executionSliderFooter"/>     <div id="vcrControls" class="btn-group">       <button id="jmpFirstInstr" class="btn-default navbar-btn" type="button"><span class="glyphicon glyphicon-backward"></span> </button>       <button id="jmpStepBack" class="btn-default navbar-btn"  type="button"><span class="glyphicon glyphicon-step-backward"></span> </button>       <span id="curInstr">Step ? of ?</span>       <button id="jmpStepFwd" class="btn-default navbar-btn"  type="button"> <span class="glyphicon glyphicon-step-forward"></span></button>       <button id="jmpLastInstr" class="btn-default navbar-btn"  type="button"> <span class="glyphicon glyphicon-forward"></span></button>     </div>     <div id="errorOutput"/>     <div id="stepAnnotationDiv">       <textarea class="annotationText" id="stepAnnotationEditor" cols="60" rows="3"></textarea>       <div class="annotationText" id="stepAnnotationViewer"></div>     </div>     <div id="annotateLinkDiv"><button id="annotateBtn" type="button">Annotate this step</button></div>     </td></tr><tr><td class="vizLayoutTd" id="vizLayoutTdSecond">'+
c+"</td></tr></table>"):this.domRoot.html('<div id="vizHeader">       <textarea class="vizTitleText" id="vizTitleEditor" cols="60" rows="1"></textarea>       <div class="vizTitleText" id="vizTitleViewer"></div>       <textarea class="vizDescriptionText" id="vizDescriptionEditor" cols="75" rows="2"></textarea>       <div class="vizDescriptionText" id="vizDescriptionViewer"></div>    </div><div id="codeDisplayDiv">       <div id="langDisplayDiv"></div>       <div id="pyCodeOutputDiv"/>       <div id="editCodeLinkDiv"><a id="editBtn">Edit code</a>       <span id="liveModeSpan" style="display: none;">| <a id="editLiveModeBtn" href="#">Live programming</a></a>       </div>       <div id="legendDiv"/>       <div id="rawUserInputDiv">       <span id="userInputPromptStr"/>       <input type="text" id="raw_input_textbox" size="30"/>       <button id="raw_input_submit_btn">Submit</button>     </div>       <div id="executionSliderDocs"><font color="#e93f34">NEW!</font> Click on a line of code to set a breakpoint. Then use the Forward and Back buttons to jump there.</div>     </div>     <div id="executionSlider"/>     <div id="executionSliderFooter"/>     <div id="vcrControls" class="btn-group">       <button id="jmpFirstInstr" class="btn-default navbar-btn" type="button"><span class="glyphicon glyphicon-backward"></span> </button>       <button id="jmpStepBack" class="btn-default navbar-btn"  type="button"><span class="glyphicon glyphicon-step-backward"></span> </button>       <span id="curInstr">Step ? of ?</span>       <button id="jmpStepFwd" class="btn-default navbar-btn"  type="button"> <span class="glyphicon glyphicon-step-forward"></span></button>       <button id="jmpLastInstr" class="btn-default navbar-btn"  type="button"> <span class="glyphicon glyphicon-forward"></span></button>     </div>     <div id="errorOutput"/>     <div id="stepAnnotationDiv">       <textarea class="annotationText" id="stepAnnotationEditor" cols="60" rows="3"></textarea>       <div class="annotationText" id="stepAnnotationViewer"></div>     </div>     <div id="annotateLinkDiv"><button id="annotateBtn" type="button">Annotate this step</button></div>     '+
c);this.showOnlyOutputs?(a.domRoot.find("#dataViz").hide(),this.domRoot.find("#vizLayoutTdSecond").append('<div id="htmlOutputDiv"></div>     <div id="progOutputs">       <div id="printOutputDocs">Print output (drag lower right corner to resize)</div>\n       <textarea id="pyStdout" cols="40" rows="5" wrap="off" readonly></textarea>     </div>'),this.params.verticalStack?this.domRoot.find("#vizLayoutTdSecond").css("padding-top","25px"):this.domRoot.find("#vizLayoutTdSecond").css("padding-left","25px")):
(c="75px",3>=this.numStdoutLines&&(c=18*this.numStdoutLines+"px"),this.params.embeddedMode&&(c="45px"),this.domRoot.find("#vizLayoutTdSecond").prepend('<div id="htmlOutputDiv"></div>     <div id="progOutputs">       <div id="printOutputDocs">Print output (drag lower right corner to resize)</div>\n       <textarea id="pyStdout" cols="40" rows="5" wrap="off" readonly></textarea>     </div>'),this.domRoot.find("#pyStdout").width("350px").height(c).resizable());this.params.arrowLines?(this.domRoot.find("#legendDiv").append('<svg id="prevLegendArrowSVG"/> line that has just executed').append('<p style="margin-top: 4px"><svg id="curLegendArrowSVG"/> next line to execute</p>'),
a.domRootD3.select("svg#prevLegendArrowSVG").append("polygon").attr("points",SVG_ARROW_POLYGON).attr("fill",lightArrowColor),a.domRootD3.select("svg#curLegendArrowSVG").append("polygon").attr("points",SVG_ARROW_POLYGON).attr("fill",darkArrowColor)):this.params.highlightLines?a.domRoot.find("#legendDiv").append('<span class="highlight-legend highlight-prev">line that has just executed</span> ').append('<span class="highlight-legend highlight-cur">next line to execute</span>'):this.params.pyCrazyMode&&
a.domRoot.find("#legendDiv").append('<a href="https://github.com/pgbovine/Py2crazy">Py2crazy</a> mode!').append(" Stepping through (roughly) each executed expression. Color codes:<p/>").append('<span class="pycrazy-highlight-prev">expression that just executed</span><br/>').append('<span class="pycrazy-highlight-cur">next expression to execute</span>');this.params.editCodeBaseURL?(c="2","js"===this.params.lang?c="js":"ts"===this.params.lang?c="ts":"java"===this.params.lang?c="java":"py3"===this.params.lang?
c="3":"c"===this.params.lang?c="c":"cpp"===this.params.lang&&(c="cpp"),c=$.param.fragment(this.params.editCodeBaseURL,{code:this.curInputCode,py:c},2),this.domRoot.find("#editBtn").attr("href",c)):(this.domRoot.find("#editCodeLinkDiv").hide(),this.domRoot.find("#editBtn").attr("href","#"),this.domRoot.find("#editBtn").click(function(){return!1}));void 0!==this.params.lang&&("js"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("JavaScript"):"ts"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("TypeScript"):
"ruby"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("Ruby"):"java"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("Java"):"py2"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("Python 2.7"):"py3"===this.params.lang?this.domRoot.find("#langDisplayDiv").html("Python 3.3"):"c"===this.params.lang?this.domRoot.find("#langDisplayDiv").html('C (gcc 4.8, C11) <font color="#e93f34">EXPERIMENTAL!</font><br/>see <a href="https://github.com/pgbovine/opt-cpp-backend/issues" target="_blank">known bugs</a> and report to philip@pgbovine.net'):
"cpp"===this.params.lang?this.domRoot.find("#langDisplayDiv").html('C++ (gcc 4.8, C++11) <font color="#e93f34">EXPERIMENTAL!</font><br/>see <a href="https://github.com/pgbovine/opt-cpp-backend/issues" target="_blank">known bugs</a> and report to philip@pgbovine.net'):this.domRoot.find("#langDisplayDiv").hide());this.allowEditAnnotations=void 0!==this.params.allowEditAnnotations?this.params.allowEditAnnotations:!1;this.pyCrazyMode=void 0!==this.params.pyCrazyMode?this.params.pyCrazyMode:!1;this.domRoot.find("#stepAnnotationEditor").hide();
this.params.embeddedMode&&(this.embeddedMode=!0,void 0===this.params.codeDivWidth&&(this.params.codeDivWidth=this.DEFAULT_EMBEDDED_CODE_DIV_WIDTH),void 0===this.params.codeDivHeight&&(this.params.codeDivHeight=this.DEFAULT_EMBEDDED_CODE_DIV_HEIGHT),this.allowEditAnnotations=!1,this.domRoot.find("#codeDisplayDiv").append('<div style="font-size: 8pt; margin-bottom: 20px;">Visualized using <a href="http://pythontutor.com" target="_blank" style="color: #3D58A2;">Online Python Tutor</a> by <a href="http://www.pgbovine.net/" target="_blank" style="color: #3D58A2;">Philip Guo</a></div>'),
a.domRoot.find("#executionSliderDocs").hide());a.editAnnotationMode=!1;if(this.allowEditAnnotations){var b=this.domRoot.find("#annotateBtn");b.click(function(){a.editAnnotationMode?(a.enterViewAnnotationsMode(),a.domRoot.find("#jmpFirstInstr,#jmpLastInstr,#jmpStepBack,#jmpStepFwd,#executionSlider,#editCodeLinkDiv,#stepAnnotationViewer").show(),a.domRoot.find("#stepAnnotationEditor").hide(),b.html("Annotate this step")):(a.enterEditAnnotationsMode(),a.domRoot.find("#jmpFirstInstr,#jmpLastInstr,#jmpStepBack,#jmpStepFwd,#executionSlider,#editCodeLinkDiv,#stepAnnotationViewer").hide(),
a.domRoot.find("#stepAnnotationEditor").show(),b.html("Done annotating"))})}else this.domRoot.find("#annotateBtn").hide();this.params.codeDivWidth&&470>this.params.codeDivWidth&&(this.domRoot.find("#jmpFirstInstr").hide(),this.domRoot.find("#jmpLastInstr").hide());this.params.codeDivWidth&&this.domRoot.find("#codeDisplayDiv").width(this.params.codeDivWidth);this.domRoot.find("#codeDisplayDiv").resizable({handles:"e",minWidth:100,resize:function(g,n){a.domRoot.find("#codeDisplayDiv").css("height",
"auto");a.renderSliderBreakpoints();a.params.updateOutputCallback&&a.params.updateOutputCallback(this)}});this.params.codeDivHeight&&this.domRoot.find("#pyCodeOutputDiv").css("max-height",this.params.codeDivHeight+"px");this.domRoot.find("#globals_area").append('<div class="stackFrame" id="'+a.generateID("globals")+'"><div id="'+a.generateID("globals_header")+'" class="stackFrameHeader">'+this.getRealLabel("Global frame")+'</div><table class="stackFrameVarTable" id="'+a.generateID("global_table")+
'"></table></div>');this.params.hideOutput&&this.domRoot.find("#progOutputs").hide();this.domRoot.find("#jmpFirstInstr").click(function(){a.renderStep(0)});this.domRoot.find("#jmpLastInstr").click(function(){a.renderStep(a.curTrace.length-1)});this.domRoot.find("#jmpStepBack").click(function(){a.stepBack()});this.domRoot.find("#jmpStepFwd").click(function(){a.stepForward()});this.domRoot.find("#vcrControls #jmpFirstInstr").attr("disabled",!0);this.domRoot.find("#vcrControls #jmpStepBack").attr("disabled",
!0);this.domRoot.find("#vcrControls #jmpStepFwd").attr("disabled",!0);this.domRoot.find("#vcrControls #jmpLastInstr").attr("disabled",!0);c=this.curTrace[this.curTrace.length-1];if(this.instrLimitReached="instruction_limit_reached"==c.event)this.curTrace.pop(),this.instrLimitReachedWarningMsg=c=c.exception_msg,a.domRoot.find("#errorOutput").html(htmlspecialchars(c)),a.domRoot.find("#errorOutput").show();c=this.domRoot.find("#executionSlider");c.slider({min:0,max:this.curTrace.length-1,step:1});c.find(".ui-slider-handle").unbind("keydown");
c.find(".ui-slider-handle").css("width","0.8em");c.find(".ui-slider-handle").css("height","1.4em");this.domRoot.find(".ui-widget-content").css("font-size","0.9em");this.domRoot.find("#executionSlider").bind("slide",function(g,n){g.originalEvent&&a.renderStep(n.value)});this.params.startingInstruction&&(this.params.jumpToEnd=!1,this.params.startingInstruction==this.curTrace.length&&this.params.startingInstruction--,0>this.params.startingInstruction&&(this.params.startingInstruction=0),this.params.startingInstruction>=
this.curTrace.length&&(this.params.startingInstruction=this.curTrace.length-1),assert(0<=this.params.startingInstruction&&this.params.startingInstruction<this.curTrace.length),this.curInstr=this.params.startingInstruction);if(this.params.jumpToEnd){c=-1;for(var k=0;k<this.curTrace.length;k++){var d=this.curTrace[k];if("exception"==d.event||"uncaught_exception"==d.event){c=k;break}}this.curInstr=0<=c?c:this.curTrace.length-1}this.params.hideCode&&this.domRoot.find("#codeDisplayDiv").hide();this.try_hook("end_render",
{myViz:this});this.precomputeCurTraceLayouts();this.params.hideCode||this.renderPyCodeOutput();this.tabularView&&(this.renderTabularView(),$(window).scroll(function(){var g=a.domRoot.find("#vizLayoutTdFirst"),n=$(document).scrollTop(),t=g.offset().top;n-=t;0>n&&(n=0);var v=a.domRoot.find("#optTabularView");v=v.height()+v.offset().top;var m=a.domRoot.find("#codeDisplayDiv").height();n-t<v-m&&g.css("padding-top",n)}));var e=a.domRoot.find("#rawUserInputDiv");e.find("#userInputPromptStr").html(a.userInputPromptStr);
e.find("#raw_input_submit_btn").click(function(){var g=e.find("#raw_input_textbox").val();a.executeCodeWithRawInputFunc(g,a.curInstr+1)});this.updateOutput();this.hasRendered=!0}};
ExecutionVisualizer.prototype.showVizHeaderViewMode=function(){var a=this.domRoot.find("#vizTitleEditor").val().trim(),c=this.domRoot.find("#vizDescriptionEditor").val().trim();this.domRoot.find("#vizTitleEditor,#vizDescriptionEditor").hide();a||c?(this.domRoot.find("#vizHeader,#vizTitleViewer,#vizDescriptionViewer").show(),a&&this.domRoot.find("#vizTitleViewer").html(htmlsanitize(a)),c&&this.domRoot.find("#vizDescriptionViewer").html(htmlsanitize(c))):this.domRoot.find("#vizHeader").hide()};
ExecutionVisualizer.prototype.showVizHeaderEditMode=function(){this.domRoot.find("#vizHeader").show();this.domRoot.find("#vizTitleViewer,#vizDescriptionViewer").hide();this.domRoot.find("#vizTitleEditor,#vizDescriptionEditor").show()};ExecutionVisualizer.prototype.destroyAllAnnotationBubbles=function(){this.allAnnotationBubbles&&$.each(this.allAnnotationBubbles,function(a,c){c.destroyQTip()});this.domRoot.find("#pyCodeOutputDiv").unbind("scroll");this.allAnnotationBubbles=null};
ExecutionVisualizer.prototype.initStepAnnotation=function(){var a=this.curTrace[this.curInstr];a.stepAnnotation?(this.domRoot.find("#stepAnnotationViewer").html(htmlsanitize(a.stepAnnotation)),this.domRoot.find("#stepAnnotationEditor").val(a.stepAnnotation)):(this.domRoot.find("#stepAnnotationViewer").html(""),this.domRoot.find("#stepAnnotationEditor").val(""))};
ExecutionVisualizer.prototype.initAllAnnotationBubbles=function(){var a=this;a.destroyAllAnnotationBubbles();var c=[];$.each(this.domRoot.find("#pyCodeOutput .cod"),function(e,g){c.push($(g).attr("id"))});var b=[];$.each(this.domRoot.find(".heapObject"),function(e,g){b.push($(g).attr("id"))});var k=[];$.each(this.domRoot.find(".variableTr"),function(e,g){k.push($(g).attr("id"))});var d=[];$.each(this.domRoot.find(".stackFrame"),function(e,g){d.push($(g).attr("id"))});a.allAnnotationBubbles=[];$.each(c,
function(e,g){a.allAnnotationBubbles.push(new AnnotationBubble(a,"codeline",g))});$.each(b,function(e,g){a.allAnnotationBubbles.push(new AnnotationBubble(a,"object",g))});$.each(k,function(e,g){a.allAnnotationBubbles.push(new AnnotationBubble(a,"variable",g))});$.each(d,function(e,g){a.allAnnotationBubbles.push(new AnnotationBubble(a,"frame",g))});this.domRoot.find("#pyCodeOutputDiv").scroll(function(){$.each(a.allAnnotationBubbles,function(e,g){"codeline"==g.type&&g.redrawCodelineBubble()})})};
ExecutionVisualizer.prototype.enterViewAnnotationsMode=function(){this.editAnnotationMode=!1;var a=this.curTrace[this.curInstr];!this.allAnnotationBubbles&&a.bubbleAnnotations&&(this.initAllAnnotationBubbles(),$.each(this.allAnnotationBubbles,function(k,d){(k=a.bubbleAnnotations[d.domID])&&d.preseedText(k)}));if(this.allAnnotationBubbles){var c={};$.each(this.allAnnotationBubbles,function(k,d){d.enterViewMode();d.text&&(c[d.domID]=d.text)});a.bubbleAnnotations=c}var b=this.domRoot.find("#stepAnnotationEditor").val().trim();
b?a.stepAnnotation=b:delete a.stepAnnotation;this.initStepAnnotation();this.showVizHeaderViewMode();this.redrawConnectors();this.redrawAllAnnotationBubbles()};
ExecutionVisualizer.prototype.enterEditAnnotationsMode=function(){this.editAnnotationMode=!0;var a=this.curTrace[this.curInstr];this.allAnnotationBubbles||this.initAllAnnotationBubbles();$.each(this.allAnnotationBubbles,function(c,b){b.enterEditMode()});a.stepAnnotation?this.domRoot.find("#stepAnnotationEditor").val(a.stepAnnotation):this.domRoot.find("#stepAnnotationEditor").val("");this.showVizHeaderEditMode();this.redrawConnectors();this.redrawAllAnnotationBubbles()};
ExecutionVisualizer.prototype.redrawAllAnnotationBubbles=function(){this.allAnnotationBubbles&&$.each(this.allAnnotationBubbles,function(a,c){c.redrawBubble()})};
ExecutionVisualizer.prototype.findPrevBreakpoint=function(){var a=this.curInstr;if(0==this.sortedBreakpointsList.length)return-1;for(var c=1;c<this.sortedBreakpointsList.length;c++){var b=this.sortedBreakpointsList[c-1];if(a<=b)return-1;if(this.sortedBreakpointsList[c]>=a)return b}c=this.sortedBreakpointsList[this.sortedBreakpointsList.length-1];return c<a?c:-1};
ExecutionVisualizer.prototype.findNextBreakpoint=function(){var a=this.curInstr;if(0==this.sortedBreakpointsList.length)return-1;if(0<=$.inArray(a,this.sortedBreakpointsList))return a+1;for(var c=0;c<this.sortedBreakpointsList.length-1;c++){var b=this.sortedBreakpointsList[c],k=this.sortedBreakpointsList[c+1];if(a<b)return b;if(b<=a&&a<k)return k}c=this.sortedBreakpointsList[this.sortedBreakpointsList.length-1];return c>a?c:-1};
ExecutionVisualizer.prototype.stepForward=function(){if(!this.editAnnotationMode){if(this.curInstr<this.curTrace.length-1){if(0<this.sortedBreakpointsList.length){var a=this.findNextBreakpoint();this.curInstr=-1!=a?a:this.curInstr+1}else this.curInstr+=1;this.updateOutput(!0);return!0}return!1}};
ExecutionVisualizer.prototype.stepBack=function(){if(!this.editAnnotationMode){if(0<this.curInstr){if(0<this.sortedBreakpointsList.length){var a=this.findPrevBreakpoint();-1!=a?this.curInstr=a:--this.curInstr}else--this.curInstr;this.updateOutput();return!0}return!1}};
ExecutionVisualizer.prototype.renderSliderBreakpoints=function(){this.domRoot.find("#executionSliderFooter").empty();var a=this.domRoot.find("#executionSlider").width(),c=this.domRootD3.select("#executionSliderFooter").append("svg").attr("id","sliderOverlay").attr("width",a).attr("height",12),b=d3.scale.linear().domain([0,this.curTrace.length-1]).range([0,a]);c.selectAll("rect").data(this.sortedBreakpointsList).enter().append("rect").attr("x",function(k,d){return 0===k?0:b(k)-1}).attr("y",0).attr("width",
2).attr("height",12).style("fill",function(k){return breakpointColor})};
ExecutionVisualizer.prototype.renderPyCodeOutput=function(){function a(){var m=[];k.breakpoints.forEach(function(l,q){m.push(Number(l))});m.sort(function(l,q){return l-q});return m}function c(m){$.each(m,function(l,q){k.breakpoints.set(q,1)});k.sortedBreakpointsList=a()}function b(m){$.each(m,function(l,q){k.breakpoints.remove(q)});k.sortedBreakpointsList=a()}var k=this;this.breakpoints=d3.map();this.sortedBreakpointsList=[];this.codeOutputLines=[];for(var d=this.curInputCode.split("\n"),e=0;e<d.length;e++){var g=
d[e],n={};n.text=g;n.lineNumber=e+1;n.executionPoints=[];n.breakpointHere=!1;$.each(this.curTrace,function(m,l){l.line==n.lineNumber&&n.executionPoints.push(m)});var t=!1;g=g.split("#");for(var v=1;v<g.length;v++)-1!=g[v].indexOf("breakpoint")&&(t=!0);t&&0<n.executionPoints.length&&(n.breakpointHere=!0,c(n.executionPoints));this.codeOutputLines.push(n)}k.domRoot.find("#pyCodeOutputDiv").empty();d=this.domRootD3.select("#pyCodeOutputDiv").append("table").attr("id","pyCodeOutput").selectAll("tr").data(this.codeOutputLines).enter().append("tr").selectAll("td").data(function(m,
l){return[m,m]}).enter().append("td").attr("class",function(m,l){return 0==l?"lineNo":"cod"}).attr("id",function(m,l){return 0==l?"lineNo"+m.lineNumber:k.generateID("cod"+m.lineNumber)}).html(function(m,l){return 0==l?m.lineNumber:htmlspecialchars(m.text)});k.params.arrowLines&&(k.domRoot.find("#pyCodeOutput tr:first").prepend('<td id="gutterTD" valign="top" rowspan="'+this.codeOutputLines.length+'"><svg id="leftCodeGutterSVG"/></td>'),k.domRootD3.select("svg#leftCodeGutterSVG").append("polygon").attr("id",
"prevLineArrow").attr("points",SVG_ARROW_POLYGON).attr("fill",lightArrowColor),k.domRootD3.select("svg#leftCodeGutterSVG").append("polygon").attr("id","curLineArrow").attr("points",SVG_ARROW_POLYGON).attr("fill",darkArrowColor));d.style("cursor",function(m,l){if((m=m.executionPoints)&&0!=m.length)return"pointer"}).on("click",function(m,l){(l=m.executionPoints)&&0!=l.length&&(m.breakpointHere=!m.breakpointHere,m.breakpointHere?(c(m.executionPoints),d3.select(this.parentNode).select("td.lineNo").style("color",
breakpointColor),d3.select(this.parentNode).select("td.lineNo").style("font-weight","bold"),d3.select(this.parentNode).select("td.cod").style("color",breakpointColor)):(b(m.executionPoints),d3.select(this.parentNode).select("td.lineNo").style("color",""),d3.select(this.parentNode).select("td.lineNo").style("font-weight",""),d3.select(this.parentNode).select("td.cod").style("color","")),k.renderSliderBreakpoints())})};
function htmlWithHighlight(a,c,b,k){var d="";0<c&&(d=a.slice(0,c));var e=a.slice(c,c+b),g="";c+b<a.length&&(g=a.slice(c+b,a.length));return htmlspecialchars(d)+'<span class="'+k+'">'+htmlspecialchars(e)+"</span>"+htmlspecialchars(g)}
ExecutionVisualizer.prototype.renderStdout=function(){var a=this.curTrace[this.curInstr];if(!this.params.hideOutput&&0<this.numStdoutLines){this.domRoot.find("#progOutputs").show();var c=this.domRoot.find("#pyStdout"),b=c.scrollLeft();c.val(a.stdout.rtrim());c.scrollLeft(b);c.scrollTop(c[0].scrollHeight)}else this.domRoot.find("#progOutputs").hide()};
ExecutionVisualizer.prototype.updateCurPrevLines=function(){var a=this.curInstr===this.curTrace.length-1;a=!this.instrLimitReached&&a;var c=null;var b=this.curTrace[this.curInstr];var k=!1,d="return"==b.event,e=!1;if(0<this.curInstr&&(c=this.curTrace[this.curInstr-1].line,e="return"==this.curTrace[this.curInstr-1].event)){var g=this.curInstr-1,n=this.curTrace[g].stack_to_render;assert(0<n.length);for(n=n[n.length-1].frame_id;0<=g;){var t=this.curTrace[g];if("call"==t.event&&t.stack_to_render&&t.stack_to_render[t.stack_to_render.length-
1].frame_id==n)break;g--}0<g&&(c=this.curTrace[g-1].line,e=!1)}if("exception"==b.event||"uncaught_exception"==b.event)assert(b.exception_msg),k=!0,this.curLineExceptionMsg=b.exception_msg;b=b.line;a&&!k&&c==b&&(b=null);this.curLineNumber=b;this.prevLineNumber=c;this.curLineIsReturn=d;this.prevLineIsReturn=e};ExecutionVisualizer.prototype.updateOutput=function(a){this.params.hideCode?this.updateOutputMini():this.updateOutputFull(a);this.renderStdout();this.try_hook("end_updateOutput",{myViz:this})};
ExecutionVisualizer.prototype.updateOutputFull=function(a){function c(){function m(y){y=b.domRoot.find("#lineNo"+y).offset().top;var D=q.offset().top,F=q.scrollTop(),K=q.height();q.stop();q.animate({scrollTop:F+(y-D-Math.round(K/2))},300)}var l=!b.instrLimitReached&&v,q=b.domRoot.find("#pyCodeOutputDiv"),p=null,r=null,f=void 0,h=void 0,u="return"==n.event,w=!1;if(0<b.curInstr){r=b.curTrace[b.curInstr-1].line;if(w="return"==b.curTrace[b.curInstr-1].event){p=b.curInstr-1;var x=b.curTrace[p].stack_to_render;
assert(0<x.length);for(x=x[x.length-1].frame_id;0<=p;){var A=b.curTrace[p];if("call"==A.event&&A.stack_to_render&&A.stack_to_render[A.stack_to_render.length-1].frame_id==x)break;p--}0<p&&(r=b.curTrace[p-1].line,a=w=!1)}b.pyCrazyMode&&(p=b.curTrace[b.curInstr-1],f=void 0!==p.expr_start_col?p.expr_start_col:p.column,h=void 0!==p.expr_width?p.expr_width:1)}p=n.line;if(b.pyCrazyMode){x=n.column;x=void 0!==n.expr_start_col?n.expr_start_col:x;A=void 0!==n.expr_width?n.expr_width:1;var C=b.codeOutputLines[p-
1];assert(C.lineNumber==p);C=C.text;$.each(b.codeOutputLines,function(y,D){y=b.generateID("cod"+D.lineNumber);b.domRoot.find("#"+y).html(htmlspecialchars(D.text))});if(r==p){for(var z="",B=0;B<C.length;B++){var G=x<=B&&B<x+A,I=f<=B&&B<f+h,E=htmlspecialchars(C[B]);z=G&&I?z+('<span class="pycrazy-highlight-prev-and-cur">'+E+"</span>"):I?z+('<span class="pycrazy-highlight-prev">'+E+"</span>"):G?z+('<span class="pycrazy-highlight-cur">'+E+"</span>"):z+E}assert(z)}else r&&(f=htmlWithHighlight(b.codeOutputLines[r-
1].text,f,h,"pycrazy-highlight-prev"),b.domRoot.find("#"+b.generateID("cod"+r)).html(f)),z=htmlWithHighlight(C,x,A,"pycrazy-highlight-cur");b.domRoot.find("#"+b.generateID("cod"+p)).html(z)}h=w?Math.floor(b.codeRowHeight/3):0;f=u?Math.floor(b.codeRowHeight/3):0;l&&!t&&(r==p?p=null:f-=2);if(b.params.arrowLines){if(r){var H=b.domRootD3.select("#prevLineArrow"),J="translate(0, "+((r-1)*b.codeRowHeight+b.arrowOffsetY+h)+")";a?H.transition().duration(200).attr("fill","white").each("end",function(){H.attr("transform",
J).attr("fill",lightArrowColor);d.find("#prevLineArrow").show()}):(H.attr("transform",J),d.find("#prevLineArrow").show())}else d.find("#prevLineArrow").hide();p?(l=b.domRootD3.select("#curLineArrow"),f="translate(0, "+((p-1)*b.codeRowHeight+b.arrowOffsetY+f)+")",a?l.transition().delay(200).duration(250).attr("transform",f):l.attr("transform",f),d.find("#curLineArrow").show()):d.find("#curLineArrow").hide()}b.domRootD3.selectAll("#pyCodeOutputDiv td.cod").style("border-top",function(y){return t&&y.lineNumber==
n.line?"1px solid "+errorColor:""}).style("border-bottom",function(y){return t&&y.lineNumber==n.line?"1px solid "+errorColor:""});b.params.highlightLines&&(b.domRoot.find("#pyCodeOutputDiv td.cod").removeClass("highlight-prev"),b.domRoot.find("#pyCodeOutputDiv td.cod").removeClass("highlight-cur"),p&&b.domRoot.find("#"+b.generateID("cod"+p)).addClass("highlight-cur"),r&&b.domRoot.find("#"+b.generateID("cod"+r)).addClass("highlight-prev"));(function(y){y=b.domRoot.find("#lineNo"+y).offset().top;var D=
q.offset().top;q.scrollTop();var F=q.height();return D<=y&&y<D+F-30})(n.line)||m(n.line);b.curLineNumber=p;b.prevLineNumber=r;b.curLineIsReturn=u;b.prevLineIsReturn=w}assert(this.curTrace);assert(!this.params.hideCode);var b=this;if(b.domRoot.is(":visible")){b.curLineNumber=void 0;b.prevLineNumber=void 0;b.curLineIsReturn=void 0;b.prevLineIsReturn=void 0;b.curLineExceptionMsg=void 0;b.codeHorizontalOverflow=b.domRoot.find("#pyCodeOutput").width()-b.domRoot.find("#pyCodeOutputDiv").width();0>b.codeHorizontalOverflow&&
(b.codeHorizontalOverflow=0);var k=b.domRoot.find("#dataViz").height(),d=b.domRoot.find("svg#leftCodeGutterSVG");if(!b.leftGutterSvgInitialized&&b.params.arrowLines){d.height(d.parent().height());var e=b.domRoot.find("table#pyCodeOutput tr:first").offset().top;b.codeRowHeight=b.domRoot.find("table#pyCodeOutput td.cod:first").height();if(this.codeOutputLines&&1<this.codeOutputLines.length){var g=b.domRoot.find("table#pyCodeOutput tr:nth-child(2)").offset().top;b.codeRowHeight=g-e}assert(0<b.codeRowHeight);
g=d.offset().top;b.arrowOffsetY=Math.floor(b.codeRowHeight/2-SVG_ARROW_HEIGHT/2)-(g-e);b.leftGutterSvgInitialized=!0}b.params.arrowLines&&(assert(void 0!==b.arrowOffsetY),assert(void 0!==b.codeRowHeight),assert(0<=b.arrowOffsetY&&b.arrowOffsetY<=b.codeRowHeight));this.params.updateOutputCallback&&this.params.updateOutputCallback(this);var n=this.curTrace[this.curInstr],t=!1;n.question&&$("#"+n.question.div).modal({position:["25%","50%"]});b.params.debugMode&&(console.log("updateOutputFull",n),b.debugMode=
!0);var v=b.curInstr==b.curTrace.length-1;b.updateVCRControls();"exception"==n.event||"uncaught_exception"==n.event?(assert(n.exception_msg),"Unknown error"==n.exception_msg?b.domRoot.find("#errorOutput").html("Unknown error: Please email a bug report to philip@pgbovine.net"):b.domRoot.find("#errorOutput").html(htmlspecialchars(n.exception_msg)),b.domRoot.find("#errorOutput").show(),t=!0,b.curLineExceptionMsg=n.exception_msg):this.instrLimitReached||b.domRoot.find("#errorOutput").hide();n.line&&c();
b.domRoot.find("#htmlOutputDiv").empty();n.html_output&&(n.css_output&&b.domRoot.find("#htmlOutputDiv").append('<style type="text/css">'+n.css_output+"</style>"),b.domRoot.find("#htmlOutputDiv").append(n.html_output),n.js_output&&b.domRoot.find("#htmlOutputDiv").append('<script type="text/javascript">'+n.js_output+"\x3c/script>"));n=this.curTrace[this.curInstr];this.renderDataStructures(n,this.curTraceLayouts[this.curInstr]);this.enterViewAnnotationsMode();b.domRoot.find("#dataViz").height()!=k&&
this.params.heightChangeCallback&&this.params.heightChangeCallback(this);k=b.domRoot.find("#rawUserInputDiv");k.hide();v&&b.executeCodeWithRawInputFunc&&b.promptForUserInput&&k.show()}};ExecutionVisualizer.prototype.updateOutputMini=function(){assert(this.params.hideCode);var a=this.curTrace[this.curInstr];this.renderDataStructures(a,this.curTraceLayouts[this.curInstr]);Blockly.mainWorkspace.traceOn(!0);Blockly.mainWorkspace.highlightBlock(a.bid);this.enterViewAnnotationsMode();this.updateVCRControls()};
ExecutionVisualizer.prototype.updateVCRControls=function(){var a=this.curTrace.length,c=this.curInstr==a-1,b=this.domRoot.find("#vcrControls");c?this.promptForUserInput||this.promptForMouseInput?b.find("#curInstr").html('<b><font color="'+brightRed+'">Enter user input below:</font></b>'):this.instrLimitReached?b.find("#curInstr").html("Instruction limit reached"):b.find("#curInstr").html("Program terminated"):b.find("#curInstr").html("Step "+String(this.curInstr+1)+" of "+String(a-1));b.find("#jmpFirstInstr").attr("disabled",
!1);b.find("#jmpStepBack").attr("disabled",!1);b.find("#jmpStepFwd").attr("disabled",!1);b.find("#jmpLastInstr").attr("disabled",!1);0==this.curInstr&&(b.find("#jmpFirstInstr").attr("disabled",!0),b.find("#jmpStepBack").attr("disabled",!0));c&&(b.find("#jmpLastInstr").attr("disabled",!0),b.find("#jmpStepFwd").attr("disabled",!0));this.domRoot.find("#executionSlider").slider("value",this.curInstr)};
ExecutionVisualizer.prototype.renderStep=function(a){assert(0<=a);assert(a<this.curTrace.length);this.curInstr!=a&&(this.curInstr=a,this.updateOutput())};ExecutionVisualizer.prototype.isCppMode=function(){return"c"===this.params.lang||"cpp"===this.params.lang};
ExecutionVisualizer.prototype.precomputeCurTraceLayouts=function(){this.curTraceLayouts=[];this.curTraceLayouts.push([]);var a=this;assert(0<this.curTrace.length);$.each(this.curTrace,function(c,b){function k(l){var q=a.try_hook("isLinearObj",{heapObj:l});return q[0]?q[1]:"LIST"==l[0]||"TUPLE"==l[0]||"SET"==l[0]}function d(l,q,p){var r=b.heap[l];if(a.isCppMode()){if(!r)return}else assert(r);k(r)?$.each(r,function(f,h){1>f||a.isPrimitiveType(h)||(f=getRefID(h),a.disableHeapNesting?e(f,[],[]):e(f,q,
p))}):"DICT"==r[0]?$.each(r,function(f,h){1>f||(a.disableHeapNesting&&(f=h[0],a.isPrimitiveType(f)||(f=getRefID(f),e(f,[],[]))),h=h[1],a.isPrimitiveType(h)||(h=getRefID(h),a.structurallyEquivalent(r,b.heap[h])?e(h,q,p):a.disableHeapNesting&&e(h,[],[])))}):"INSTANCE"==r[0]||"CLASS"==r[0]?jQuery.each(r,function(f,h){f<("INSTANCE"==r[0]?2:3)||(a.disableHeapNesting&&(f=h[0],a.isPrimitiveType(f)||(f=getRefID(f),e(f,[],[]))),h=h[1],a.isPrimitiveType(h)||(h=getRefID(h),a.structurallyEquivalent(r,b.heap[h])?
e(h,q,p):a.disableHeapNesting&&e(h,[],[])))}):("C_ARRAY"==r[0]||"C_STRUCT"==r[0])&&g(r)}function e(l,q,p){if(!m.has(l)){a:{for(var r=0;r<t.length;r++){var f=t[r];var h=f.indexOf(l);if(0<h){f={row:f,index:h};break a}}f=null}r=m.has(l);m.set(l,1);if(f){q=f.row;f=f.index;v.remove(l);if(!r&&1<p.length){f=[f,0];for(r=1;r<p.length;r++)f.push(p[r]),v.remove(p[r]);q.splice.apply(q,f);p.splice(0,p.length)}d(l,q,[])}else if(0==p.length&&p.push("row"+l),p.push(l),d(l,q,p),0<p.length){if(q&&0<q.length)for(r=
1;r<p.length;r++)q.push(p[r]);else t.push($.extend(!0,[],p));for(r=1;r<p.length;r++)v.remove(p[r]);p.splice(0,p.length)}}}function g(l){if(l){if(isHeapRef(l,b.heap)){var q=getRefID(l);e(q,null,[])}n(l)}}function n(l){"C_ARRAY"===l[0]?$.each(l,function(q,p){2>q||g(p)}):"C_STRUCT"===l[0]&&$.each(l,function(q,p){3>q||g(p[1])})}var t=$.extend(!0,[],a.curTraceLayouts[a.curTraceLayouts.length-1]),v=d3.map();$.each(t,function(l,q){for(l=1;l<q.length;l++)v.set(q[l],1)});var m=d3.map();$.each(b.ordered_globals,
function(l,q){l=b.globals[q];void 0!==l&&(a.isCppMode()?g(l):a.isPrimitiveType(l)||(l=getRefID(l),e(l,null,[])))});$.each(b.stack_to_render,function(l,q){$.each(q.ordered_varnames,function(p,r){p=q.encoded_locals[r];a.isCppMode()?g(p):a.isPrimitiveType(p)||(p=getRefID(p),e(p,null,[]))})});v.forEach(function(l,q){l=Number(l);$.each(t,function(p,r){p=r.indexOf(l);0<p&&r.splice(p,1)})});t=t.filter(function(l){return 1<l.length});a.curTraceLayouts.push(t)});this.curTraceLayouts.splice(0,1);assert(this.curTrace.length==
this.curTraceLayouts.length)};var heapPtrSrcRE=/__heap_pointer_src_/,rightwardNudgeHack=!0;
ExecutionVisualizer.prototype.renderDataStructures=function(a,c){function b(f,h){e.isCppMode()?e.domRoot.find("#"+h).length?e.jsPlumbInstance.connect({source:f,target:h,scope:"varValuePointer"}):e.domRoot.find("#"+f).html("\ud83d\udca9"):e.jsPlumbInstance.connect({source:f,target:h,scope:"varValuePointer"})}function k(f,h){0!=e.domRoot.find("#"+f).length&&0!=e.domRoot.find("#"+h).length&&(e.jsPlumbInstance.connect({source:f,target:h,anchors:["LeftMiddle","LeftMiddle"],connector:["Bezier",{curviness:45}],
endpoint:["Dot",{radius:4}],scope:"frameParentPointer"}),p++)}function d(f){e.jsPlumbInstance.select().each(function(h){var u=h.source.closest(".stackFrame");u.attr("id")==f?(h.setPaintStyle({lineWidth:1,strokeStyle:connectorBaseColor}),h.endpoints[0].setPaintStyle({fillStyle:connectorBaseColor}),$(h.canvas).css("z-index",1E3)):!e.jsPlumbManager.heapConnectionEndpointIDs.has(h.endpoints[0].elementId)&&0<u.length&&(h.setPaintStyle({lineWidth:1,strokeStyle:connectorInactiveColor}),h.endpoints[0].setPaintStyle({fillStyle:connectorInactiveColor}),
$(h.canvas).css("z-index",0))});e.domRoot.find(".stackFrame").removeClass("highlightedStackFrame");e.domRoot.find("#"+f).addClass("highlightedStackFrame")}var e=this;if(!e.tabularView){e.resetJsPlumbManager();var g=d3.map();e.jsPlumbInstance.select({scope:"varValuePointer"}).each(function(f){f.sourceId.match(heapPtrSrcRE)||g.set(f.sourceId,f.targetId)});var n=d3.map();e.jsPlumbInstance.select({scope:"frameParentPointer"}).each(function(f){n.set(f.sourceId,f.targetId)});$.each(c,function(f,h){for(f=
0;f<h.length;f++){var u=e.generateHeapObjID(h[f],e.curInstr);e.jsPlumbManager.renderedHeapObjectIDs.set(u,1)}});e.domRoot.find("#heap").empty().html('<div id="heapHeader">Objects</div>');c=e.domRootD3.select("#heap").selectAll("table.heapRow").attr("id",function(f,h){return"heapRow"+h}).data(c,function(f){return f[0]});c.enter().append("table").attr("id",function(f,h){return"heapRow"+h}).attr("class","heapRow");c.exit().each(function(f,h){$(this).empty()}).remove();c=c.selectAll("td.toplevelHeapObject").data(function(f,
h){return f.slice(1,f.length)},function(f){return f});c.enter().append("td").attr("class","toplevelHeapObject").attr("id",function(f,h){return"toplevel_heap_object_"+f});c.order().each(function(f,h){$(this).empty();e.isCppMode()?void 0!==a.heap[f]&&e.renderCompoundObject(f,e.curInstr,$(this),!0):e.renderCompoundObject(f,e.curInstr,$(this),!0)});c.exit().each(function(f,h){$(this).empty()}).remove();var t=[];$.each(a.ordered_globals,function(f,h){void 0!==a.globals[h]&&t.push(h)});var v=e.generateID("globals");
c=e.generateID("global_table");c=e.domRootD3.select("#"+c).selectAll("tr").data(t,function(f){return f});c.enter().append("tr").attr("class","variableTr").attr("id",function(f,h){return e.generateID(varnameToCssID("global__"+f+"_tr"))});var m=c.selectAll("td.stackFrameVar,td.stackFrameValue").data(function(f,h){return[f,f]});m.enter().append("td").attr("class",function(f,h){return 0==h?"stackFrameVar":"stackFrameValue"});m.order().each(function(f,h){if(0==h)$(this).html(f);else if($(this).empty(),
h=e.generateID("global__"+varnameToCssID(f)),g.remove(h),f=a.globals[f],e.isPrimitiveType(f))e.renderPrimitiveObject(f,$(this));else if("C_STRUCT"===f[0]||"C_ARRAY"===f[0])e.renderCStructArray(f,e.curInstr,$(this));else{var u=e.generateHeapObjID(getRefID(f),e.curInstr);if(e.textualMemoryLabels){var w=h+"_text_label";$(this).append('<div class="objectIdLabel" id="'+w+'">id'+getRefID(f)+"</div>");$(this).find("div#"+w).hover(function(){e.jsPlumbInstance.connect({source:w,target:u,scope:"varValuePointer"})},
function(){e.jsPlumbInstance.select({source:w}).detach()})}else $(this).append('<div class="stack_pointer" id="'+h+'">&nbsp;</div>'),assert(!e.jsPlumbManager.connectionEndpointIDs.has(h)),e.jsPlumbManager.connectionEndpointIDs.set(h,u)}});m.exit().each(function(f,h){$(this).empty()}).remove();c.exit().each(function(f,h){$(this).find(".stack_pointer").each(function(u,w){g.remove($(w).attr("id"))});$(this).empty()}).remove();0==a.ordered_globals.length?this.domRoot.find("#"+v).hide():this.domRoot.find("#"+
v).show();c=e.domRootD3.select("#stack").selectAll("div.stackFrame,div.zombieStackFrame").data(a.stack_to_render,function(f){return f.unique_hash});m=c.enter().append("div").attr("class",function(f,h){return f.is_zombie?"zombieStackFrame":"stackFrame"}).attr("id",function(f,h){return f.is_zombie?e.generateID("zombie_stack"+h):e.generateID("stack"+h)}).attr("data-frame_id",function(f,h){return f.frame_id}).attr("data-parent_frame_id",function(f,h){return 0<f.parent_frame_id_list.length?f.parent_frame_id_list[0]:
null}).each(function(f,h){if(e.drawParentPointers){var u=$(this).attr("id");0<f.parent_frame_id_list.length?e.domRoot.find("div#stack [data-frame_id="+f.parent_frame_id_list[0]+"]").each(function(w,x){w=$(this).attr("id");e.jsPlumbManager.parentPointerConnectionEndpointIDs.set(u,w)}):0<a.ordered_globals.length&&e.jsPlumbManager.parentPointerConnectionEndpointIDs.set(u,v);e.domRoot.find("div#stack [data-parent_frame_id="+f.frame_id+"]").each(function(w,x){w=$(this).attr("id");e.jsPlumbManager.parentPointerConnectionEndpointIDs.set(w,
u)})}});m.append("div").attr("class","stackFrameHeader").html(function(f,h){h=htmlspecialchars(f.func_name).replace("&lt;lambda&gt;","\u03bb").replace("\n","<br/>");if(f.is_parent||e.showAllFrameLabels)h="f"+f.frame_id+": "+h;0<f.parent_frame_id_list.length?h=h+" [parent=f"+f.parent_frame_id_list[0]+"]":e.showAllFrameLabels&&(h+=" [parent=Global]");return h});m.append("table").attr("class","stackFrameVarTable");m=c.order().select("table").selectAll("tr").data(function(f){return f.ordered_varnames.map(function(h){return{varname:h,
frame:f}})},function(f){if(f)return f.varname});m.enter().append("tr").attr("class","variableTr").attr("id",function(f,h){return e.generateID(varnameToCssID(f.frame.unique_hash+"__"+f.varname+"_tr"))});var l=m.selectAll("td.stackFrameVar,td.stackFrameValue").data(function(f,h){return[f,f]});l.enter().append("td").attr("class",function(f,h){return 0==h?"stackFrameVar":"stackFrameValue"});l.order().each(function(f,h){var u=f.varname;f=f.frame;if(0==h)"__return__"==u?$(this).html('<span class="retval">Return<br/>value</span>'):
$(this).html(u);else if($(this).empty(),h=e.generateID(varnameToCssID(f.unique_hash+"__"+u)),g.remove(h),u=f.encoded_locals[u],e.isPrimitiveType(u))e.renderPrimitiveObject(u,$(this));else if("C_STRUCT"===u[0]||"C_ARRAY"===u[0])e.renderCStructArray(u,e.curInstr,$(this));else{var w=e.generateHeapObjID(getRefID(u),e.curInstr);if(e.textualMemoryLabels){var x=h+"_text_label";$(this).append('<div class="objectIdLabel" id="'+x+'">id'+getRefID(u)+"</div>");$(this).find("div#"+x).hover(function(){e.jsPlumbInstance.connect({source:x,
target:w,scope:"varValuePointer"})},function(){e.jsPlumbInstance.select({source:x}).detach()})}else $(this).append('<div class="stack_pointer" id="'+h+'">&nbsp;</div>'),assert(!e.jsPlumbManager.connectionEndpointIDs.has(h)),e.jsPlumbManager.connectionEndpointIDs.set(h,w)}});l.exit().each(function(f,h){$(this).empty()}).remove();m.exit().each(function(f,h){$(this).find(".stack_pointer").each(function(u,w){g.remove($(w).attr("id"))});$(this).empty()}).remove();c.exit().each(function(f,h){$(this).find(".stack_pointer").each(function(w,
x){g.remove($(x).attr("id"))});var u=$(this).attr("id");n.forEach(function(w,x){w!=u&&x!=u||n.remove(w)});$(this).empty()}).remove();if(rightwardNudgeHack){var q={};c=e.jsPlumbManager.heapConnectionEndpointIDs.keys();c.sort();$.each(c,function(f,h){f=e.jsPlumbManager.heapConnectionEndpointIDs.get(h);var u=e.domRoot.find("#"+h);h=u.closest(".heapObject");f=e.domRoot.find("#"+f);assert("heapObject"==f.attr("class"));var w=h.closest(".heapRow"),x=f.closest(".heapRow"),A=w.attr("id");w=x.attr("id");if(A!=
w&&(u=u.offset().left,h.offset(),h=f.offset().left,u>h)){var C=u-h+32;f.css("margin-left","+="+C);var z=q[A];void 0===z&&(z=d3.map(),q[A]=z);z.set(w,1);(h=q[w])&&h.forEach(function(B,G){B!=A&&(e.domRoot.find("#"+B).css("margin-left","+="+C),z.set(B,1))})}})}e.jsPlumbInstance.reset();var p=0;e.textualMemoryLabels||(e.isCppMode()||g.forEach(b),e.jsPlumbManager.connectionEndpointIDs.forEach(b));e.drawParentPointers&&(n.forEach(k),e.jsPlumbManager.parentPointerConnectionEndpointIDs.forEach(k));var r=
!1;$.each(a.stack_to_render,function(f,h){h.is_highlighted&&(d(e.generateID("stack"+f)),r=!0)});r||d(e.generateID("globals"));e.try_hook("end_renderDataStructures",{myViz:e})}};
ExecutionVisualizer.prototype.renderTabularView=function(){function a(v){var m=[""];$.each(b,function(q,p){m.push(v.globals[p])});var l=null;$.each(v.stack_to_render,function(q,p){p.is_highlighted&&(l=p)});$.each(d,function(q,p){$.each(k[p],function(r,f){r=!1;l&&p==l.func_name&&(f=l.encoded_locals[f])&&(m.push(f),r=!0);r||m.push(void 0)})});return m}var c=this;c.resetJsPlumbManager();var b=[],k={},d=[];$.each(c.curTrace,function(v,m){$.each(m.ordered_globals,function(l,q){-1===$.inArray(q,b)&&b.push(q)});
$.each(m.stack_to_render,function(l,q){var p=k[q.func_name];void 0===p&&(p=[],k[q.func_name]=p,d.push(q.func_name));$.each(q.ordered_varnames,function(r,f){-1===$.inArray(f,p)&&"__return__"!==f&&p.push(f)})})});var e=["Step"];$.each(b,function(v,m){e.push(m)});$.each(d,function(v,m){$.each(k[m],function(l,q){e.push(m+":"+q)})});var g=c.domRootD3.select("#optTabularView").append("table");g.attr("id","optTable");var n=g.append("thead").attr("class","stepTableThead").append("tr");n.attr("class","stepTableTr");
n.selectAll("thead td").data(e).enter().append("td").attr("class","stepTableTd").html(function(v){return v});g=g.append("tbody");g.attr("class","stepTableTbody");var t=[];$.each(c.curTrace,function(v,m){t.push([v,m])});g.selectAll("tbody tr").data(t).enter().append("tr").attr("step",function(v,m){return m}).attr("class","stepTableTr").selectAll("td").data(function(v){return a(v[1])}).enter().append("td").attr("class","stepTableTd").each(function(v,m){$(this).empty();var l=parseInt($(this).closest("tr").attr("step"));
0==m?$(this).html(l+1):void 0!==v&&c.renderNestedObject(v,l,$(this),"tabular")});c.jsPlumbInstance.reset();c.jsPlumbManager.connectionEndpointIDs.forEach(function(v,m){c.jsPlumbInstance.connect({source:v,target:m,scope:"varValuePointer",anchors:["TopCenter","LeftMiddle"]})})};
ExecutionVisualizer.prototype.renderPrimitiveObject=function(a,c){if(!this.try_hook("renderPrimitiveObject",{obj:a,d3DomElement:c})[0]){var b=typeof a;if(null==a)c.append('<span class="nullObj">'+this.getRealLabel("None")+"</span>");else if("number"==b)c.append('<span class="numberObj">'+a+"</span>");else if("boolean"==b)a?c.append('<span class="boolObj">'+this.getRealLabel("True")+"</span>"):c.append('<span class="boolObj">'+this.getRealLabel("False")+"</span>");else if("string"==b)a=htmlspecialchars(a),
a=a.replace(/\n/g,"<br/>"),a=a.replace(/"/g,'\\"'),c.append('<span class="stringObj">"'+(a+'"</span>'));else if("object"==b)if("C_DATA"==a[0]){var k=a[2];"short int"===k?k="short":"short unsigned int"===k?k="unsigned short":"long int"===k?k="long":"long long int"===k?k="long long":"long unsigned int"===k?k="unsigned long":"long long unsigned int"===k&&(k="unsigned long long int");var d="pointer"===k&&"<UNINITIALIZED>"!==a[3]&&"<UNALLOCATED>"!==a[3],e=a[1],g="";this.debugMode&&(g=e+"<br/>");b=this.generateHeapObjID("cdata_"+
e,this.curInstr);d?(c.append('<div id="'+b+'" class="cdataHeader">'+g+k+"</div>"),a=a[3],b=this.generateHeapObjID("ptrSrc_"+e,this.curInstr),a=this.generateHeapObjID("cdata_"+a,this.curInstr),e="",this.debugMode&&(e=a),c.append('<div style="width: 10px;" id="'+b+'" class="cdataElt">&nbsp;'+e+"</div>"),assert(!this.jsPlumbManager.connectionEndpointIDs.has(b)),this.jsPlumbManager.connectionEndpointIDs.set(b,a)):(c.append('<div class="cdataHeader">'+g+k+"</div>"),"string"===typeof a[3]?(a=a[3],"<UNINITIALIZED>"===
a?a='<span class="cdataUninit">?</span>':"<UNALLOCATED>"==a?a="\ud83d\udc80":(a=a.replace(/\n/g,"\\n"),a=a.replace(/\t/g,"\\t"),a=a.replace(/"/g,'\\"'),a=htmlspecialchars("'"+a+"'"))):a=htmlspecialchars(a[3]),c.append('<div id="'+b+'" class="cdataElt">'+a+"</div>"))}else assert("SPECIAL_FLOAT"==a[0]||"JS_SPECIAL_VAL"==a[0]),c.append('<span class="numberObj">'+a[1]+"</span>");else assert(!1)}};
ExecutionVisualizer.prototype.renderNestedObject=function(a,c,b){this.isPrimitiveType(a)?this.renderPrimitiveObject(a,b):"REF"===a[0]?this.renderCompoundObject(getRefID(a),c,b,!1):(assert("C_STRUCT"===a[0]||"C_ARRAY"===a[0]),this.renderCStructArray(a,c,b))};
ExecutionVisualizer.prototype.renderCompoundObject=function(a,c,b,k){var d=this,e=d.generateHeapObjID(a,c);if(!k&&d.jsPlumbManager.renderedHeapObjectIDs.has(e)){var g=d.generateID("heap_pointer_src_"+d.jsPlumbManager.heap_pointer_src_id);d.jsPlumbManager.heap_pointer_src_id++;if(d.textualMemoryLabels){var n=g+"_text_label";b.append('<div class="objectIdLabel" id="'+n+'">id'+a+"</div>");d.domRoot.find("div#"+n).hover(function(){d.jsPlumbInstance.connect({source:n,target:e,scope:"varValuePointer"})},
function(){d.jsPlumbInstance.select({source:n}).detach()})}else b.append('<div id="'+g+'">&nbsp;</div>'),assert(!d.jsPlumbManager.connectionEndpointIDs.has(g)),d.jsPlumbManager.connectionEndpointIDs.set(g,e),assert(!d.jsPlumbManager.heapConnectionEndpointIDs.has(g)),d.jsPlumbManager.heapConnectionEndpointIDs.set(g,e)}else{b.append('<div class="heapObject" id="'+e+'"></div>');b=d.domRoot.find("#"+e);d.jsPlumbManager.renderedHeapObjectIDs.set(e,1);g=d.curTrace[c].heap[a];assert($.isArray(g));var t=
"";d.textualMemoryLabels&&(t="id"+a+":");if(!d.try_hook("renderCompoundObject",{objID:a,d3DomElement:b,isTopLevel:k,obj:g,typeLabelPrefix:t,stepNum:c,myViz:d})[0])if("LIST"==g[0]||"TUPLE"==g[0]||"SET"==g[0]||"DICT"==g[0]){var v=g[0].toLowerCase();assert(1<=g.length);if(1==g.length)b.append('<div class="typeLabel">'+t+" empty "+d.getRealLabel(v)+"</div>");else{b.append('<div class="typeLabel">'+t+d.getRealLabel(v)+"</div>");b.append('<table class="'+v+'Tbl"></table>');var m=b.children("table");if("LIST"==
g[0]||"TUPLE"==g[0]){m.append("<tr></tr><tr></tr>");var l=m.find("tr:first"),q=m.find("tr:last");$.each(g,function(h,u){1>h||(l.append('<td class="'+v+'Header"></td>'),l.find("td:last").append(h-1),q.append('<td class="'+v+'Elt"></td>'),d.renderNestedObject(u,c,q.find("td:last")))})}else if("SET"==g[0]){t=g.length-1;a=Math.round(Math.sqrt(t));3<a&&--a;var p=Math.round(t/a);t%a&&(p+=1);jQuery.each(g,function(h,u){1>h||(0==(h-1)%p&&m.append("<tr></tr>"),h=m.find("tr:last"),h.append('<td class="setElt"></td>'),
d.renderNestedObject(u,c,h.find("td:last")))})}else"DICT"==g[0]&&$.each(g,function(h,u){if(!(1>h)){m.append('<tr class="dictEntry"><td class="dictKey"></td><td class="dictVal"></td></tr>');var w=m.find("tr:last");h=w.find("td:first");w=w.find("td:last");var x=u[1];d.renderNestedObject(u[0],c,h);d.renderNestedObject(x,c,w)}})}}else if("INSTANCE"==g[0]||"CLASS"==g[0]){var r=(a="INSTANCE"==g[0])?2:3;assert(g.length>=r);a?b.append('<div class="typeLabel">'+t+g[1]+" "+d.getRealLabel("instance")+"</div>"):
(k="",0<g[2].length&&(k+="[extends "+g[2].join(", ")+"] "),b.append('<div class="typeLabel">'+t+g[1]+" class "+k+'<br/><a href="#" id="attrToggleLink">hide attributes</a></div>'));if(g.length>r){var f=a?"inst":"class";b.append('<table class="'+f+'Tbl"></table>');m=b.children("table");$.each(g,function(h,u){if(!(h<r)){m.append('<tr class="'+f+'Entry"><td class="'+f+'Key"></td><td class="'+f+'Val"></td></tr>');var w=m.find("tr:last");h=w.find("td:first");w=w.find("td:last");if("string"==typeof u[0]){var x=
htmlspecialchars(u[0]);h.append('<span class="keyObj">'+x+"</span>")}else d.renderNestedObject(u[0],c,h);d.renderNestedObject(u[1],c,w)}})}a||($(b.selector+" .typeLabel #attrToggleLink").click(function(){var h=$(b.selector+" .classTbl");h.toggle();$(this).html((h.is(":visible")?"hide":"show")+" attributes");h.is(":visible")?(d.classAttrsHidden[b.selector]=!1,$(this).html("hide attributes")):(d.classAttrsHidden[b.selector]=!0,$(this).html("show attributes"));d.redrawConnectors();return!1}),d.classAttrsHidden[b.selector]&&
($(b.selector+" .classTbl").hide(),$(b.selector+" .typeLabel #attrToggleLink").html("show attributes")))}else"INSTANCE_PPRINT"==g[0]?(b.append('<div class="typeLabel">'+t+g[1]+" instance</div>"),g=htmlspecialchars(g[2]),b.append('<table class="customObjTbl"><tr><td class="customObjElt">'+g+"</td></tr></table>")):"FUNCTION"==g[0]?(assert(3==g.length),a=htmlspecialchars(g[1]).replace("&lt;lambda&gt;","\u03bb"),g=g[2],d.compactFuncLabels||b.append('<div class="typeLabel">'+t+d.getRealLabel("function")+
"</div>"),t=d.compactFuncLabels?"func":"",g?b.append('<div class="funcObj">'+t+" "+a+" [parent=f"+g+"]</div>"):d.showAllFrameLabels?b.append('<div class="funcObj">'+t+" "+a+" [parent=Global]</div>"):b.append('<div class="funcObj">'+t+" "+a+"</div>")):"JS_FUNCTION"==g[0]?(assert(5==g.length),a=htmlspecialchars(g[1]),t+=htmlspecialchars(g[2]),a=g[3],g=g[4],a||g||d.showAllFrameLabels?(b.append('<table class="classTbl"></table>'),m=b.children("table"),m.append('<tr><td class="funcCod" colspan="2"><pre class="funcCode">'+
t+"</pre></td></tr>"),a&&(assert(0<a.length),$.each(a,function(h,u){m.append('<tr class="classEntry"><td class="classKey"></td><td class="classVal"></td></tr>');var w=m.find("tr:last");h=w.find("td:first");w=w.find("td:last");h.append('<span class="keyObj">'+htmlspecialchars(u[0])+"</span>");d.renderNestedObject(u[1],c,w)})),g?m.append('<tr class="classEntry"><td class="classKey">parent</td><td class="classVal">f'+g+"</td></tr>"):d.showAllFrameLabels&&m.append('<tr class="classEntry"><td class="classKey">parent</td><td class="classVal">global</td></tr>')):
b.append('<pre class="funcCode">'+t+"</pre>")):"HEAP_PRIMITIVE"==g[0]?(assert(3==g.length),a=g[1],g=g[2],b.append('<div class="heapPrimitive"></div>'),b.find("div.heapPrimitive").append('<div class="typeLabel">'+t+a+"</div>"),d.renderPrimitiveObject(g,b.find("div.heapPrimitive"))):"C_STRUCT"==g[0]||"C_ARRAY"==g[0]?d.renderCStructArray(g,c,b):(assert(2==g.length),a=g[0],g=g[1],g=htmlspecialchars(g),b.append('<div class="typeLabel">'+t+a+"</div>"),b.append('<table class="customObjTbl"><tr><td class="customObjElt">'+
g+"</td></tr></table>"))}};
ExecutionVisualizer.prototype.renderCStructArray=function(a,c,b){var k=this;if("C_STRUCT"==a[0]){assert(3<=a.length);var d=a[1],e=a[2],g="";k.debugMode&&(g=d+"<br/>");"cpp"===k.params.lang?b.append('<div class="typeLabel">'+g+"object "+e+"</div>"):b.append('<div class="typeLabel">'+g+"struct "+e+"</div>");if(3<a.length){b.append('<table class="instTbl"></table>');var n=b.children("table");$.each(a,function(m,l){if(!(3>m)){n.append('<tr class="instEntry"><td class="instKey"></td><td class="instVal"></td></tr>');var q=
n.find("tr:last");m=q.find("td:first");q=q.find("td:last");assert("string"==typeof l[0]);var p=htmlspecialchars(l[0]);m.append('<span class="keyObj">'+p+"</span>");k.renderNestedObject(l[1],c,q)}})}}else{assert("C_ARRAY"==a[0]);assert(2<=a.length);d=a[1];g="";k.debugMode&&(g=d+"<br/>");b.append('<div class="typeLabel">'+g+"array</div>");b.append('<table class="cArrayTbl"></table>');n=b.children("table");n.append("<tr></tr><tr></tr>");var t=n.find("tr:first"),v=n.find("tr:last");$.each(a,function(m,
l){2>m||(t.append('<td class="cArrayHeader"></td>'),t.find("td:last").append(m-2),v.append('<td class="cArrayElt"></td>'),k.renderNestedObject(l,c,v.find("td:last")))})}};ExecutionVisualizer.prototype.redrawConnectors=function(){this.jsPlumbInstance.repaintEverything()};
ExecutionVisualizer.prototype.getRealLabel=function(a){if("js"===this.params.lang||"ts"===this.params.lang||"ruby"===this.params.lang){if("list"===a)return"array";if("instance"===a)return"object";if("True"===a)return"true";if("False"===a)return"false"}if("js"===this.params.lang){if("dict"===a)return"Map";if("set"===a)return"Set"}if("ruby"===this.params.lang){if("dict"===a)return"hash";if("set"===a)return"Set";if("function"===a)return"method";if("None"===a)return"nil";if("Global frame"===a)return"Global Object"}return a};
var highlightedLineColor="#e4faeb",highlightedLineBorderColor="#005583",highlightedLineLighterColor="#e8fff0",funcCallLineColor="#a2eebd",brightRed="#e93f34",connectorBaseColor="#005583",connectorHighlightColor=brightRed,connectorInactiveColor="#cccccc",errorColor=brightRed,breakpointColor=brightRed,darkArrowColor=brightRed,lightArrowColor="#c9e6ca";function assert(a){if(!a)throw alert("Assertion Failure (see console log for backtrace)"),"Assertion Failure";}
function htmlspecialchars(a){"string"==typeof a&&(a=a.replace(/&/g,"&amp;"),a=a.replace(/</g,"&lt;"),a=a.replace(/>/g,"&gt;"),a=a.replace(/ /g,"&nbsp;"),a=a.replace(/\t/g,"&nbsp;&nbsp;&nbsp;&nbsp;"));return a}function htmlsanitize(a){"string"==typeof a&&(a=a.replace(/&/g,"&amp;"),a=a.replace(/</g,"&lt;"),a=a.replace(/>/g,"&gt;"));return a}String.prototype.rtrim=function(){return this.replace(/\s*$/g,"")};var lbRE=/\[|{|\(|</g,rbRE=/\]|}|\)|>/g;
function varnameToCssID(a){return a.replace(lbRE,"LeftB_").replace(rbRE,"_RightB").replace(/[!]/g,"_BANG_").replace(/[?]/g,"_QUES_").replace(/[:]/g,"_COLON_").replace(/[=]/g,"_EQ_").replace(/[.]/g,"_DOT_").replace(/ /g,"_")}
ExecutionVisualizer.prototype.structurallyEquivalent=function(a,c){if(this.isPrimitiveType(a)||this.isPrimitiveType(c)||a[0]!=c[0]||a.length!=c.length)return!1;if("LIST"!=a[0]&&"TUPLE"!=a[0]){if("DICT"==a[0])var b=2;else if("INSTANCE"==a[0])b=3;else return!1;for(var k=d3.map(),d=b;d<a.length;d++)k.set(a[d][0],1);for(d=b;d<c.length;d++)if(!k.has(c[d][0]))return!1}return!0};
ExecutionVisualizer.prototype.isPrimitiveType=function(a){var c=this.try_hook("isPrimitiveType",{obj:a});return c[0]?c[1]:null===a?!0:"object"==typeof a?"SPECIAL_FLOAT"==a[0]||"JS_SPECIAL_VAL"==a[0]||"C_DATA"==a[0]:!0};function isHeapRef(a,c){return"REF"===a[0]?void 0!==c[a[1]]:"C_DATA"===a[0]&&"pointer"===a[2]&&"<UNINITIALIZED>"!=a[3]&&"<UNALLOCATED>"!=a[3]?void 0!==c[a[3]]:!1}
function getRefID(a){if("REF"==a[0])return a[1];assert("C_DATA"===a[0]&&"pointer"===a[2]);assert("<UNINITIALIZED>"!=a[3]&&"<UNALLOCATED>"!=a[3]);return a[3]}var qtipShared={show:{ready:!0,delay:0,event:null,effect:function(){$(this).show()}},hide:{fixed:!0,event:null,effect:function(){$(this).hide()}},style:{classes:"ui-tooltip-pgbootstrap"}};
function AnnotationBubble(a,c,b){this.parentViz=a;this.domID=b;this.hashID="#"+b;this.type=c;"codeline"==c?(this.my="left center",this.at="right center"):"frame"==c?(this.my="right center",this.at="left center"):"variable"==c?(this.my="right center",this.at="left center"):"object"==c?(this.my="bottom left",this.at="top center"):assert(!1);this.state="invisible";this.text="";this.qtipHidden=!1}
AnnotationBubble.prototype.showStub=function(){assert("invisible"==this.state||"edit"==this.state);assert(""==this.text);var a=this;this.destroyQTip();$(this.hashID).qtip($.extend({},qtipShared,{content:" ",id:this.domID,position:{my:this.my,at:this.at,adjust:{x:"codeline"==a.type?-6:0},effect:null},style:{classes:"ui-tooltip-pgbootstrap ui-tooltip-pgbootstrap-stub"}}));$(this.qTipID()).unbind("click").click(function(){a.showEditor()});this.state="stub"};
AnnotationBubble.prototype.showEditor=function(){assert("stub"==this.state||"view"==this.state||"minimized"==this.state);var a=this,c='<textarea class="bubbleInputText">'+this.text+"</textarea>";this.destroyQTip();$(this.hashID).qtip($.extend({},qtipShared,{content:c,id:this.domID,position:{my:this.my,at:this.at,adjust:{x:"codeline"==a.type?-6:0},effect:null}}));$(this.qTipContentID()).find("textarea.bubbleInputText").blur(function(){a.text=$(this).val().trim();a.text?a.showViewer():a.showStub()}).focus();
this.state="edit"};AnnotationBubble.prototype.bindViewerClickHandler=function(){var a=this;$(this.qTipID()).unbind("click").click(function(){a.parentViz.editAnnotationMode?a.showEditor():a.minimizeViewer()})};
AnnotationBubble.prototype.showViewer=function(){assert("edit"==this.state||"invisible"==this.state);assert(this.text);this.destroyQTip();$(this.hashID).qtip($.extend({},qtipShared,{content:htmlsanitize(this.text),id:this.domID,position:{my:this.my,at:this.at,adjust:{x:"codeline"==this.type?-6:0},effect:null}}));this.bindViewerClickHandler();this.state="view"};
AnnotationBubble.prototype.minimizeViewer=function(){assert("view"==this.state);var a=this;$(this.hashID).qtip("option","content.text"," ");$(this.qTipID()).unbind("click").click(function(){a.parentViz.editAnnotationMode?a.showEditor():a.restoreViewer()});this.state="minimized"};AnnotationBubble.prototype.restoreViewer=function(){assert("minimized"==this.state);$(this.hashID).qtip("option","content.text",htmlsanitize(this.text));this.bindViewerClickHandler();this.state="view"};
AnnotationBubble.prototype.makeInvisible=function(){assert("stub"==this.state||"edit"==this.state);this.destroyQTip();this.state="invisible"};AnnotationBubble.prototype.destroyQTip=function(){$(this.hashID).qtip("destroy")};AnnotationBubble.prototype.qTipContentID=function(){return"#ui-tooltip-"+this.domID+"-content"};AnnotationBubble.prototype.qTipID=function(){return"#ui-tooltip-"+this.domID};
AnnotationBubble.prototype.enterEditMode=function(){assert(this.parentViz.editAnnotationMode);"invisible"==this.state&&(this.showStub(),"codeline"==this.type&&this.redrawCodelineBubble())};
AnnotationBubble.prototype.enterViewMode=function(){assert(!this.parentViz.editAnnotationMode);"stub"==this.state?this.makeInvisible():"edit"==this.state?(this.text=$(this.qTipContentID()).find("textarea.bubbleInputText").val().trim())?(this.showViewer(),"codeline"==this.type&&this.redrawCodelineBubble()):this.makeInvisible():"invisible"==this.state&&this.text&&(this.showViewer(),"codeline"==this.type&&this.redrawCodelineBubble())};
AnnotationBubble.prototype.preseedText=function(a){assert("invisible"==this.state);this.text=a};AnnotationBubble.prototype.redrawCodelineBubble=function(){assert("codeline"==this.type);isOutputLineVisibleForBubbles(this.domID)?(this.qtipHidden?$(this.hashID).qtip("show"):$(this.hashID).qtip("reposition"),this.qtipHidden=!1):($(this.hashID).qtip("hide"),this.qtipHidden=!0)};AnnotationBubble.prototype.redrawBubble=function(){$(this.hashID).qtip("reposition")};
function isOutputLineVisibleForBubbles(a){var c=$("#pyCodeOutputDiv");a=$("#"+a).offset().top;var b=c.offset().top;c.scrollTop();c=c.height();return b<=a&&a<b+c-25}function traceQCheckMe(a,c,b){var k=$("#"+c).data("vis"),d=k.curInstr,e=k.curTrace[d+1];a=$("#"+a).val();b=b.split(".");for(var g in b)e=e[b[g]];c=$("#"+c+"_feedbacktext");0<a.length&&a==e?c.html("Correct"):c.html(k.curTrace[d].question.feedback)}function closeModal(a){$.modal.close();$("#"+a).data("vis").stepForward()}
ExecutionVisualizer.prototype.activateJavaFrontend=function(){var a=null;this.curTrace.forEach(function(d,e){"exception"!==d.event||d.line||(d.line=a);void 0!==d.stack_to_render&&d.stack_to_render.reverse();a=d.line});this.add_pytutor_hook("renderPrimitiveObject",function(d){var e=d.obj;d=d.d3DomElement;var g=typeof e;if(null==e)d.append('<span class="nullObj">null</span>');else if("number"==g)d.append('<span class="numberObj">'+e+"</span>");else if("boolean"==g)e?d.append('<span class="boolObj">true</span>'):
d.append('<span class="boolObj">false</span>');else if(e instanceof Array&&"VOID"==e[0])d.append('<span class="voidObj">void</span>');else if(e instanceof Array&&"NUMBER-LITERAL"==e[0])d.append('<span class="numberObj">'+e[1]+"</span>");else if(e instanceof Array&&"CHAR-LITERAL"==e[0]){g=e[1].charCodeAt(0);e=e[1];for(var n=g.toString(16);4>n.length;)n="0"+n;n="\\u"+n;"\n"==e?n="\\n":"\r"==e?n="\\r":"\t"==e?n="\\t":"\b"==e?n="\\b":"\f"==e?n="\\f":"'"==e?n="\\'":'"'==e?n='\\"':"\\"==e?n="\\\\":32<=
g&&(n=e);d.append('<span class="stringObj">\''+n+"'</span>")}else return[!1];return[!0]});this.add_pytutor_hook("isPrimitiveType",function(d){d=d.obj;return d instanceof Array&&"VOID"==d[0]||d instanceof Array&&"NUMBER-LITERAL"==d[0]||d instanceof Array&&"CHAR-LITERAL"==d[0]||d instanceof Array&&"ELIDE"==d[0]?[!0,!0]:[!1]});this.add_pytutor_hook("end_updateOutput",function(d){d=d.myViz;var e=d.curTrace[d.curInstr];d.params.stdin&&""!=d.params.stdin&&(e=e.stdinPosition||0,e='<span style="color:lightgray;text-decoration: line-through">'+
k(d.params.stdin.substr(0,e))+"</span>"+k(d.params.stdin.substr(e)),d.domRoot.find("#stdinShow").html(e));return[!1]});this.add_pytutor_hook("end_constructor",function(d){d=d.myViz;0<d.curTrace.length&&d.curTrace[d.curTrace.length-1]&&d.curTrace[d.curTrace.length-1].stdout?(d.hasStdout=!0,d.stdoutLines=d.curTrace[d.curTrace.length-1].stdout.split("\n").length):1<d.curTrace.length&&d.curTrace[d.curTrace.length-2]&&d.curTrace[d.curTrace.length-2].stdout?(d.hasStdout=!0,d.stdoutLines=d.curTrace[d.curTrace.length-
2].stdout.split("\n").length):d.stdoutLines=-1;if(d.hasStdout)for(var e=0;e<d.curTrace.length;e++)d.curTrace[e].stdout||(d.curTrace[e].stdout=" ")});this.add_pytutor_hook("end_render",function(d){d=d.myViz;d.params.stdin&&""!=d.params.stdin&&d.domRoot.find("#dataViz").append('<div id="stdinWrap">stdin:<pre id="stdinShow" style="border:1px solid gray"></pre></div>');d.domRoot.find("#"+d.generateID("globals_header")).html("Static fields")});this.add_pytutor_hook("isLinearObject",function(d){d=d.heapObj;
return"STACK"==d[0]||"QUEUE"==d[0]?["true","true"]:["false"]});this.add_pytutor_hook("renderCompoundObject",function(d){var e=d.d3DomElement,g=d.obj,n=d.typeLabelPrefix,t=d.myViz,v=d.stepNum;if("LIST"!=g[0]&&"QUEUE"!=g[0]&&"STACK"!=g[0])return[!1];var m=g[0].toLowerCase();d={list:"array",queue:"queue",stack:"stack"}[m];if(1==g.length)return e.append('<div class="typeLabel">'+n+"empty "+d+"</div>"),[!0];e.append('<div class="typeLabel">'+n+d+"</div>");e.append('<table class="'+m+'Tbl"></table>');e=
e.children("table");if("LIST"==g[0]){e.append("<tr></tr><tr></tr>");n=e.find("tr:first");var l=e.find("tr:last");d=1;for(var q=0;d<g.length;d++){var p=g[d],r=p instanceof Array&&"ELIDE"==p[0];n.append('<td class="'+m+'Header"></td>');n.find("td:last").append(r?"&hellip;":q);l.append('<td class="'+m+'Elt"></td>');r?(l.find("td:last").append("&hellip;"),q+=p[1]):(t.renderNestedObject(p,v,l.find("td:last")),q++)}}"STACK"==g[0]&&(e.append("<tr></tr><tr></tr>"),l=e.find("tr:last"),l.append('<td class="'+
m+'FElt"><span class="stringObj symbolic">&#8596;</span></td>'),$.each(g,function(f,h){1>f||(l.append('<td class="'+m+'Elt"></td>'),t.renderNestedObject(h,v,l.find("td:last")))}),l.append('<td class="'+m+'LElt"></td>'));"QUEUE"==g[0]&&(e.append("<tr></tr><tr></tr>"),l=e.find("tr:last"),l.append('<td class="'+m+'FElt"><span class="stringObj symbolic">&#8592;</span></td>'),$.each(g,function(f,h){1>f||(l.append('<td class="'+m+'Elt"></td>'),t.renderNestedObject(h,v,l.find("td:last")))}),l.append('<td class="'+
m+'LElt"><span class="stringObj symbolic">&#8592;</span></td>'));return[!0]});this.add_pytutor_hook("end_renderDataStructures",function(d){d=d.myViz;d.domRoot.find("td.instKey:contains('___NO_LABEL!___')").hide();d.domRoot.find(".typeLabel:contains('dict')").each(function(e){"dict"==$(this).html()&&$(this).html("symbol table");"empty dict"==$(this).html()&&$(this).html("empty symbol table")})});var c=ExecutionVisualizer.prototype.generateID.bind(this);this.generateID=function(d){d=d.replace(/[^0-9a-zA-Z_]/g,
function(e){return"-"+e.charCodeAt(0)+"-"});return c(d)};var b={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"},k=function(d){return String(d).replace(/[&<>"'\/]/g,function(e){return b[e]})}};
